on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 测试步骤一
        # uses: jinzhijiang/docker-action-fabric@v1.0.0
        uses: ./
        id: hello
        with:
          # rsakey: ${{ secrets.SSH_RSA }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          ip: ${{ secrets.SSH_IP }}
          user: ${{ secrets.SSH_USR }}
          run: |
            local('pwd')
            local('ls')
            put('README.md', "/home/README2.md")
      - name: 获取结果
        run: echo "Result = ${{ steps.hello.outputs.result }}"
